# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nllint < Formula
  desc "Check newlines at the end of files"
  homepage "https://github.com/suzuki-shunsuke/nllint"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.0/nllint_darwin_arm64.tar.gz"
      sha256 "336accc20169d49eba7ddbcf030758be2dc6655bc3ec2f2ac03de833ce35492e"

      def install
        bin.install "nllint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.0/nllint_darwin_amd64.tar.gz"
      sha256 "c576ec52a5777255c074b0c20cdcd83060e4e502bc1fea05ee8b149b35a0867f"

      def install
        bin.install "nllint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.0/nllint_linux_arm64.tar.gz"
      sha256 "f51b84dca69c8aecd992c606d23f735ec37be692cef2e895270b8e72b84183c4"

      def install
        bin.install "nllint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.0/nllint_linux_amd64.tar.gz"
      sha256 "8ab2cb63a60ccd8fdc9e0f71b7fd2d9b7374054dea5f8ae63dd2e3e7d233686d"

      def install
        bin.install "nllint"
      end
    end
  end

  test do
    system "#{bin}/nllint --version"
  end
end
