# This file was generated by GoReleaser. DO NOT EDIT.
cask "nllint" do
  desc "Check newlines at the end of files"
  homepage "https://github.com/suzuki-shunsuke/nllint"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nllint"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.2/nllint_darwin_amd64.tar.gz"
      sha256 "ead8931e0f048904e9d85e45e90f4e3bdf13b5d2ee5f2bccc35782bc3ec4cd8f"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.2/nllint_darwin_arm64.tar.gz"
      sha256 "0db73e6dc366fbb1eabaae3d65c9c1e2f8b8dd09d9022d436d46120dbd5b96fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.2/nllint_linux_amd64.tar.gz"
      sha256 "f903f622df9c89a694bec4218ac2957d1e579627b662df92e53ff725a9597e5d"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.2/nllint_linux_arm64.tar.gz"
      sha256 "fe2f89e5b03a1ebf6079071ca5e2836350735a6b1000c975ae27525c4c077488"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nllint"]
    end
  end

  # No zap stanza required
end
