# This file was generated by GoReleaser. DO NOT EDIT.
cask "nllint" do
  name "nllint"
  desc "Check newlines at the end of files"
  homepage "https://github.com/suzuki-shunsuke/nllint"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nllint"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v#{version}/nllint_darwin_amd64.tar.gz"
      sha256 "5733518d44f7eae2b4b16b0ea6617597c89b2eb084a4e6101a1dc03716266b6c"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v#{version}/nllint_darwin_arm64.tar.gz"
      sha256 "e854ee0aa0dd83273d3b68e335bc025fda721a32a3373091dfdec3a582d1ec41"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v#{version}/nllint_linux_amd64.tar.gz"
      sha256 "f54ec24ce1c344b611f6d80155396101d38e72b7f88e2ca8b9bfadc16307ae35"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v#{version}/nllint_linux_arm64.tar.gz"
      sha256 "ec8d94494c70f4285a39375f385a4e52f945c597a3a5361adf3dd9f1c8263ce4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nllint"]
    end
  end

  # No zap stanza required
end
