# This file was generated by GoReleaser. DO NOT EDIT.
cask "nllint" do
  desc "Check newlines at the end of files"
  homepage "https://github.com/suzuki-shunsuke/nllint"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nllint"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.1/nllint_darwin_amd64.tar.gz"
      sha256 "1092e6afdb83f381f17d72ad74ee572c2956aeffb0c80cdb3d94cffc41f74467"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.1/nllint_darwin_arm64.tar.gz"
      sha256 "f7a4e2600cd7341f4c1dc62e29c7d6144a56e59ccff33a944fc4530666c4daab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.1/nllint_linux_amd64.tar.gz"
      sha256 "6cd530aa22e2ce46014c1bf29878b0b7c1b417d0fbd52f38860ceaca6dc794d1"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/nllint/releases/download/v0.1.1/nllint_linux_arm64.tar.gz"
      sha256 "c6cee8098af1055e9d16c2b6bd070e5a1898e513a554db6d2cb2493b061c7133"
    end
  end

  # No zap stanza required
end
